configDependencies:
  '@pnpm/plugin-types-fixer': 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==
engineStrict: true
gitChecks: false
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.14'
  - '@biomejs/cli-darwin-arm64@2.5.14'
  - '@biomejs/cli-darwin-x64@2.5.14'
  - '@biomejs/cli-linux-arm64-musl@2.5.14'
  - '@biomejs/cli-linux-arm64@2.5.14'
  - '@biomejs/cli-linux-x64-musl@2.5.14'
  - '@biomejs/cli-linux-x64@2.5.14'
  - '@biomejs/cli-win32-arm64@2.5.14'
  - '@biomejs/cli-win32-x64@2.5.14'
  - '@cspell/cspell-bundled-dicts@10.3.3'
  - '@cspell/cspell-json-reporter@10.3.3'
  - '@cspell/cspell-performance-monitor@10.3.3'
  - '@cspell/cspell-pipe@10.3.3'
  - '@cspell/cspell-resolver@10.3.3'
  - '@cspell/cspell-service-bus@10.3.3'
  - '@cspell/cspell-types@10.3.3'
  - '@cspell/cspell-worker@10.3.3'
  - '@cspell/dynamic-import@10.3.3'
  - '@cspell/filetypes@10.3.3'
  - '@cspell/rpc@10.3.3'
  - '@cspell/strong-weak-map@10.3.3'
  - '@cspell/url@10.3.3'
  - cspell-config-lib@10.3.3
  - cspell-dictionary@10.3.3
  - cspell-gitignore@10.3.3
  - cspell-glob@10.3.3
  - cspell-grammar@10.3.3
  - cspell-io@10.3.3
  - cspell-lib@10.3.3
  - cspell-trie-lib@10.3.3
  - cspell@10.3.3
minimumReleaseAgeExcludePrune: true
minimumReleaseAgeStrict: true
pmOnFail: warn
shellEmulator: true
update:
  changeset: true
  githubActions: true
virtualStoreType: global
